### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by AurevoirXavier** [substrate-developer-hub/substrate-seminar#52]
The most recent commit was made 7 months ago.

It appears that all previous crowdcast videos have been deleted from the server.
When I click on replay, the console displays a 404 error.

**Comment by sacha-l** [comment]
Unfortunately it has been completely dead since I left Parity. But I've been thinking about moving it to become community owned and support maintainers and streamers by treasury funding. Would this be something you would support?

Regarding the videos, you can find them in the Parity tech youtube playlists (up to 2022) for e.g. [here](https://www.youtube.com/watch?v=9nBGSMs8XM8&list=PLp0_ueXY_enVAh4AfpAJtdBNCxL_eCs9K) or some older ones on Crowdcast (for e.g. the one you did [here](https://www.crowdcast.io/e/substrate-seminar-2/26)) and all the more recent ones on the Polkadot Youtube [seminars playlist](https://www.youtube.com/playlist?list=PLOyWqupZ-WGsfgxkwTdMOwnbRW4nx_T-i).

**Comment by flipchan** [comment]
> But I've been thinking about moving it to become community owned and support maintainers and streamers by treasury funding. Would this be something you would support?

 I would support this 110%, you should do it

**Comment by sacha-l** [comment]
Let's DM about it -- @sacha-lansky:matrix.org 🌈
